2025-09-13 17:44:52,432 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/sql_keyword.yaml
2025-09-13 17:44:52,456 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/sql_keyword.yaml
2025-09-13 17:44:52,456 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/xml_parser_config.yaml
2025-09-13 17:44:52,462 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/xml_parser_config.yaml
2025-09-13 17:44:52,463 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/sql_keyword.yaml
2025-09-13 17:44:52,485 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/sql_keyword.yaml
2025-09-13 17:44:52,486 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/xml_parser_config.yaml
2025-09-13 17:44:52,492 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/xml_parser_config.yaml
2025-09-13 17:44:52,502 - SourceAnalyzer - DEBUG - logger.py:64 - 데이터베이스 연결 성공: projects/sampleSrc/metadata.db
2025-09-13 17:44:52,502 - SourceAnalyzer - DEBUG - logger.py:64 - 쿼리 실행 성공: 
                SELECT COUNT(*) as count 
       ...
2025-09-13 17:44:52,503 - SourceAnalyzer - DEBUG - logger.py:64 - 데이터베이스 연결 성공: projects/sampleSrc/metadata.db
2025-09-13 17:44:52,503 - SourceAnalyzer - DEBUG - logger.py:64 - 쿼리 실행 성공: SELECT table_id FROM tables WHERE table_name = ?...
2025-09-13 17:44:52,504 - SourceAnalyzer - DEBUG - logger.py:64 - 데이터베이스 연결 성공: projects/sampleSrc/metadata.db
2025-09-13 17:44:52,504 - SourceAnalyzer - ERROR - logger.py:76 - 데이터베이스 연결 오류: table columns has no column named is_primary_key
2025-09-13 17:44:52,508 - SourceAnalyzer - ERROR - logger.py:128 - FATAL ERROR at D:\Analyzer\CreateMetaDb\util\database_utils.py:196 in execute_update()
Code: cursor.execute(query, params)
Message: 업데이트 쿼리 실행 실패: 
            INSERT OR REPLACE INTO columns (table...
Exception: OperationalError: table columns has no column named is_primary_key
Stack Trace:
Traceback (most recent call last):
  File "D:\Analyzer\CreateMetaDb\util\database_utils.py", line 196, in execute_update
    cursor.execute(query, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: table columns has no column named is_primary_key

