2025-09-13 17:43:38,605 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/sql_keyword.yaml
2025-09-13 17:43:38,632 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/sql_keyword.yaml
2025-09-13 17:43:38,633 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/xml_parser_config.yaml
2025-09-13 17:43:38,641 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/xml_parser_config.yaml
2025-09-13 17:43:38,643 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/sql_keyword.yaml
2025-09-13 17:43:38,667 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/sql_keyword.yaml
2025-09-13 17:43:38,668 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/xml_parser_config.yaml
2025-09-13 17:43:38,676 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/xml_parser_config.yaml
2025-09-13 17:43:38,693 - SourceAnalyzer - ERROR - logger.py:128 - FATAL ERROR at D:\Analyzer\CreateMetaDb\parser\xml_parser.py:1301 in _column_exists_in_schema()
Code: db_utils = DatabaseUtils()
Message: 컬럼 존재 확인 실패
Exception: TypeError: DatabaseUtils.__init__() missing 1 required positional argument: 'db_path'
Stack Trace:
Traceback (most recent call last):
  File "D:\Analyzer\CreateMetaDb\parser\xml_parser.py", line 1301, in _column_exists_in_schema
    db_utils = DatabaseUtils()
TypeError: DatabaseUtils.__init__() missing 1 required positional argument: 'db_path'

